name: CD deploy container to Amazon EKS
on: 
  pull_request:
    branches:
    - main
    #paths:
    #- 'manifest/**'

jobs:
  deploy-to-EKS:
    name: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    #- name: validate
    #  uses: 
    - name: login to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: set kubectl
      uses: azure/setup-kubectl@v1
    - name: deploy
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo "$KUBE_CONFIG" > /tmp/kubeconfig
        export KUBECONFIG=/tmp/kubeconfig
        kubectl apply -f manifest/